### ISSUE TITLE
Audio become mute when start recording.

### ISSUE THREAD

**Issue by hyunki** [muaz-khan/Chrome-Extensions#13]
Literally, audio doesn't work when I click the recording button.
Audio in recorded video is working fine.

**Comment by muaz-khan** [comment]
`tabCapture` API mutes the tab's audios.

Do NOT select following from the "options" page; because it tries to use tabCapture API:

![tabcapture](https://cloud.githubusercontent.com/assets/477092/23820987/e8e0c6fc-0647-11e7-9e2b-76550c193fbe.png)

Set following instead; because it uses desktopCapture API:

![desktopcapture](https://cloud.githubusercontent.com/assets/477092/23820989/fb0903e4-0647-11e7-950e-7a067388e379.png)
