### ISSUE TITLE
Instructions result in hung screen

### ISSUE THREAD

**Issue by rretter** [muaz-khan/Chrome-Extensions#14]
Hello,

I have installed your "WebRTC Desktop Sharing" Chrome extension from the Chrome store onto Chrome Version 57.0.2987.98 (current as of today) on 2 PCs.

As directed by the instructions on page https://github.com/muaz-khan/Chrome-Extensions/tree/master/desktopCapture-p2p, I opened the following link in Chrome on both PCs: 

https://webrtcweb.com/screen?s=your_room_id

I provided a name for "your_room_id" and used it on both PCs.  Both went through a few steps and then hung at displaying "Screen share session is closed or paused. You will join automatically when share session is resumed."

What am I doing wrong?  I imagine there exists somewhere further info on how to try out your extension.  Perhaps it can be inferred from wading through source code.  But the existence of instructions on https://github.com/muaz-khan/Chrome-Extensions/tree/master/desktopCapture-p2p gave me the impression that the instructions would work, so I am left wondering why this is not so.

Thank you for any help you may provide.

**Comment by Xanthony89X** [comment]
Hello what can i help u with


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: rretter <notifications@github.com> Date: 3/10/17  11:56 AM  (GMT-06:00) To: muaz-khan/Chrome-Extensions <Chrome-Extensions@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [muaz-khan/Chrome-Extensions] Instructions result in hung screen (#14) 
Hello,
I have installed your "WebRTC Desktop Sharing" Chrome extension from the Chrome store onto Chrome Version 57.0.2987.98 (current as of today) on 2 PCs.
As directed by the instructions on page https://github.com/muaz-khan/Chrome-Extensions/tree/master/desktopCapture-p2p, I opened the following link in Chrome on both PCs:
https://webrtcweb.com/screen?s=your_room_id
I provided a name for "your_room_id" and used it on both PCs.  Both went through a few steps and then hung at displaying "Screen share session is closed or paused. You will join automatically when share session is resumed."
What am I doing wrong?  I imagine there exists somewhere further info on how to try out your extension.  Perhaps it can be inferred from wading through source code.  But the existence of instructions on https://github.com/muaz-khan/Chrome-Extensions/tree/master/desktopCapture-p2p gave me the impression that the instructions would work, so I am left wondering why this is not so.
Thank you for any help you may provide.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/muaz-khan/Chrome-Extensions","title":"muaz-khan/Chrome-Extensions","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/muaz-khan/Chrome-Extensions"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Instructions result in hung screen (#14)"}],"action":{"name":"View Issue","url":"https://github.com/muaz-khan/Chrome-Extensions/issues/14"}}}
