### ISSUE TITLE
The "matches" URL in manifest.json file should be wide open

### ISSUE THREAD

**Issue by danny-swimmer** [muaz-khan/Chrome-Extensions#16]
Please consider changing the "matches" URL in manifest.json file to be wide open, like this:
"matches": ["https://*/*", "https://www.webrtc-experime...", "https://rtcmulticonnection...."]

This would remove the need for every user of getScreenId to publish a chrome extension in Google App Store.

**Comment by muaz-khan** [comment]
The extension will get-disabled for all users each time when we add new URL in the `matches` list. More than 50% users simply uninstall.

We don't need multiple URLs because we have this solution:

* https://github.com/muaz-khan/getScreenId

getScreenId works on all HTTPs domains, conditions:

1. Domains MUST be using HTTPs protocol (SSL enabled)
2. Webpages MUST NOT be using `<iframe>`. getScreenId do NOT supports `<iframe>`.

getScreenId fails on `jsfiddle.net` because they embeds iframes. getScreenId works on ally HTTPs webpages, though.

Upload this HTML on google-drive, drop-box or your own HTTPs domain, and it will work:

* https://github.com/muaz-khan/getScreenId/blob/master/index.html

**Comment by danny-swimmer** [comment]
Hi Muaz,

Sorry, but I don't understand your reply.

My question relates to the following line from getScreen.js from [here](https://webrtcexperiment-webrtc.netdna-ssl.com/getScreenId.js):
<       iframe.src = 'https://www.webrtc-experiment.com/getSourceId/'; // https://wwww.yourdomain.com/getScreenId.html >

We are using the portion of the line that is commented-out above (https://wwww.yourdomain.com/getScreenId.html).

We are successfully hosting getScreenId.html on our local embedded server, because our users may not have internet access. It's all working fine. The only drawback is that we had to publish our own version of your Chrome desktopCapture extension, as documented [here](https://github.com/muaz-khan/Chrome-Extensions/tree/master/desktopCapture), to include our domain in the "matches" field at line 17 of the manifest.json file.

All we are suggesting is that you consider making the "matches" URL wide open, so other users like us won't have to publish their own version of your Chrome desktopCapture extension.

**Comment by muaz-khan** [comment]
I've a question: **Why do you need getScreenId if you deployed chrome extension yourself?**

You should use this one instead (of using getScreenId):

* https://github.com/muaz-khan/Chrome-Extensions/tree/master/Screen-Capturing.js
