### ISSUE TITLE
YouTube upload failed

### ISSUE THREAD

**Issue by vm-sct** [muaz-khan/Chrome-Extensions#42]
For chrome extension "RecordRTC" (Screen recording), Popup shows **"Authorization page could not be loaded"** when clicked on button "Upload to YouTube" after video is recorded on preview screen.
Chrome version 67.0.3396.99

**Comment by muaz-khan** [comment]
Please make sure that you're using this chrome extension:
* https://chrome.google.com/webstore/detail/recordrtc/ndcljioonkecdnaaihodjgiliohngojp

Make sure that you're not using the source-code of [screen-recording](https://github.com/muaz-khan/Chrome-Extensions/tree/master/screen-recording) extension.

**Otherwise** you have to modify [`manifest.json`](https://github.com/muaz-khan/Chrome-Extensions/blob/master/screen-recording/manifest.json#L47) for `oauth2` values.

```json
{  
   "oauth2": {
       "client_id": "41556190767-44cbqasurg3dhfr9hmj1v90q5v8r9v46.apps.googleusercontent.com",
       "scopes": [
         "https://www.googleapis.com/auth/youtube.upload",
         "https://www.googleapis.com/auth/youtube"
       ]
   }
}
```

Where `client_id` must be an ID that is allocated to your extension via [this page](https://console.developers.google.com/apis/credentials?project=)
